name: Python Lint Test

on:
  push:
    paths:
      - '**.py'

jobs:
  Python_Lint_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install flake8
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --ignore=E501,E116,W293,W605,F841 --max-complexity=30 --builtins="_" --show-source --statistics
